//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.View.Finance.LetterOfCredits {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResLetterOfCredit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResLetterOfCredit() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.View.Finance.LetterOfCredits.ResLetterOfCredit", typeof(ResLetterOfCredit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Acceptance Date In Advance 的本地化字符串。
        /// </summary>
        public static string AcceptanceDateInAdvance {
            get {
                return ResourceManager.GetString("AcceptanceDateInAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acceptance Due Date 的本地化字符串。
        /// </summary>
        public static string AcceptanceDueDate {
            get {
                return ResourceManager.GetString("AcceptanceDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add BL 的本地化字符串。
        /// </summary>
        public static string AddBL {
            get {
                return ResourceManager.GetString("AddBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Invoice 的本地化字符串。
        /// </summary>
        public static string AddInvoice {
            get {
                return ResourceManager.GetString("AddInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applicant BP 的本地化字符串。
        /// </summary>
        public static string ApplyBP {
            get {
                return ResourceManager.GetString("ApplyBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select application BP! 的本地化字符串。
        /// </summary>
        public static string ApplyBPNotNull {
            get {
                return ResourceManager.GetString("ApplyBPNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Beneficiary BP is required! 的本地化字符串。
        /// </summary>
        public static string BenbifitBPNotNull {
            get {
                return ResourceManager.GetString("BenbifitBPNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Beneficiary BP 的本地化字符串。
        /// </summary>
        public static string BenefitBP {
            get {
                return ResourceManager.GetString("BenefitBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Issuing Detail of the Month 的本地化字符串。
        /// </summary>
        public static string CurrentMonthIssues {
            get {
                return ResourceManager.GetString("CurrentMonthIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discount Interest 的本地化字符串。
        /// </summary>
        public static string DiscountInterest {
            get {
                return ResourceManager.GetString("DiscountInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discount Interest Rate 的本地化字符串。
        /// </summary>
        public static string DiscountInterestRate {
            get {
                return ResourceManager.GetString("DiscountInterestRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Float 的本地化字符串。
        /// </summary>
        public static string Float {
            get {
                return ResourceManager.GetString("Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Informing Bank 的本地化字符串。
        /// </summary>
        public static string InformBank {
            get {
                return ResourceManager.GetString("InformBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interest 的本地化字符串。
        /// </summary>
        public static string Interest {
            get {
                return ResourceManager.GetString("Interest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calculation of interest errs. The detail:  的本地化字符串。
        /// </summary>
        public static string InterestError {
            get {
                return ResourceManager.GetString("InterestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interest Rate 的本地化字符串。
        /// </summary>
        public static string InterestRate {
            get {
                return ResourceManager.GetString("InterestRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Issue 的本地化字符串。
        /// </summary>
        public static string Issue {
            get {
                return ResourceManager.GetString("Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Issuing Bank 的本地化字符串。
        /// </summary>
        public static string IssueBank {
            get {
                return ResourceManager.GetString("IssueBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To 的本地化字符串。
        /// </summary>
        public static string IssueEndDate {
            get {
                return ResourceManager.GetString("IssueEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Letter of Credit - Issuing 的本地化字符串。
        /// </summary>
        public static string IssueLoC {
            get {
                return ResourceManager.GetString("IssueLoC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Issued From 的本地化字符串。
        /// </summary>
        public static string IssueStartDate {
            get {
                return ResourceManager.GetString("IssueStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Issuing Quantity 的本地化字符串。
        /// </summary>
        public static string IssuingQty {
            get {
                return ResourceManager.GetString("IssuingQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Shipment Date 的本地化字符串。
        /// </summary>
        public static string LatestShipDate {
            get {
                return ResourceManager.GetString("LatestShipDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not get the LIBOR currenly. Please select other LIBOR type and try again!  的本地化字符串。
        /// </summary>
        public static string LIBORError {
            get {
                return ResourceManager.GetString("LIBORError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LIBOR Type 的本地化字符串。
        /// </summary>
        public static string LIBORType {
            get {
                return ResourceManager.GetString("LIBORType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select LoC Currency! 的本地化字符串。
        /// </summary>
        public static string LoCCurrencyNotNull {
            get {
                return ResourceManager.GetString("LoCCurrencyNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoC Deadline 的本地化字符串。
        /// </summary>
        public static string LoCDeadline {
            get {
                return ResourceManager.GetString("LoCDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loc Due Date 的本地化字符串。
        /// </summary>
        public static string LoCDueDate {
            get {
                return ResourceManager.GetString("LoCDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoC Existed! 的本地化字符串。
        /// </summary>
        public static string LoCExisted {
            get {
                return ResourceManager.GetString("LoCExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Letter of Credit 的本地化字符串。
        /// </summary>
        public static string LoCHome {
            get {
                return ResourceManager.GetString("LoCHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List of Letter of Credit 的本地化字符串。
        /// </summary>
        public static string LoCList {
            get {
                return ResourceManager.GetString("LoCList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input LoC No.! 的本地化字符串。
        /// </summary>
        public static string LoCNoNotNull {
            get {
                return ResourceManager.GetString("LoCNoNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoC not found! 的本地化字符串。
        /// </summary>
        public static string LoCNotFound {
            get {
                return ResourceManager.GetString("LoCNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Letter of Credit - Release 的本地化字符串。
        /// </summary>
        public static string LoCRelease {
            get {
                return ResourceManager.GetString("LoCRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoC Status 的本地化字符串。
        /// </summary>
        public static string LoCStatus {
            get {
                return ResourceManager.GetString("LoCStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select LoC Status! 的本地化字符串。
        /// </summary>
        public static string LoCStatusNotNull {
            get {
                return ResourceManager.GetString("LoCStatusNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoC Type 的本地化字符串。
        /// </summary>
        public static string LoCType {
            get {
                return ResourceManager.GetString("LoCType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select LoC type! 的本地化字符串。
        /// </summary>
        public static string LoCTypeNotNull {
            get {
                return ResourceManager.GetString("LoCTypeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nullify LoC 的本地化字符串。
        /// </summary>
        public static string NullifyLoC {
            get {
                return ResourceManager.GetString("NullifyLoC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Receive 的本地化字符串。
        /// </summary>
        public static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Released Amount 的本地化字符串。
        /// </summary>
        public static string ReleaseAmount {
            get {
                return ResourceManager.GetString("ReleaseAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Released Date 的本地化字符串。
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To 的本地化字符串。
        /// </summary>
        public static string ReleaseEndDate {
            get {
                return ResourceManager.GetString("ReleaseEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Release From 的本地化字符串。
        /// </summary>
        public static string ReleaseStartDate {
            get {
                return ResourceManager.GetString("ReleaseStartDate", resourceCulture);
            }
        }
    }
}
