//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.View.SystemSetting.BusinessPartnerSetting {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResBusinessPartnerSetting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResBusinessPartnerSetting() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.View.SystemSetting.BusinessPartnerSetting.ResBusinessPartnerSetting", typeof(ResBusinessPartnerSetting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BankList.
        /// </summary>
        public static string BankList {
            get {
                return ResourceManager.GetString("BankList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BP Code.
        /// </summary>
        public static string BPCode {
            get {
                return ResourceManager.GetString("BPCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BP Code is already Existed!.
        /// </summary>
        public static string BPCodeExisted {
            get {
                return ResourceManager.GetString("BPCodeExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BP Code is Required!.
        /// </summary>
        public static string BPCodeRequired {
            get {
                return ResourceManager.GetString("BPCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string BPFullName {
            get {
                return ResourceManager.GetString("BPFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BP Home.
        /// </summary>
        public static string BPHome {
            get {
                return ResourceManager.GetString("BPHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BP List.
        /// </summary>
        public static string BPList {
            get {
                return ResourceManager.GetString("BPList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Name.
        /// </summary>
        public static string BPShortName {
            get {
                return ResourceManager.GetString("BPShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BP Type.
        /// </summary>
        public static string BPType {
            get {
                return ResourceManager.GetString("BPType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed Address.
        /// </summary>
        public static string DetailedAddress {
            get {
                return ResourceManager.GetString("DetailedAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Address.
        /// </summary>
        public static string EnglishAddress {
            get {
                return ResourceManager.GetString("EnglishAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name (EN).
        /// </summary>
        public static string EnglishFullName {
            get {
                return ResourceManager.GetString("EnglishFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name is Required!.
        /// </summary>
        public static string FullNameRequired {
            get {
                return ResourceManager.GetString("FullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Short Name is already Existed!.
        /// </summary>
        public static string ShortNameExisted {
            get {
                return ResourceManager.GetString("ShortNameExisted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Full Name is already Existed!.
        /// </summary>
        public static string FullNameExisted
        {
            get
            {
                return ResourceManager.GetString("FullNameExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Name is Required!.
        /// </summary>
        public static string ShortNameRequired {
            get {
                return ResourceManager.GetString("ShortNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Id.
        /// </summary>
        public static string TaxId {
            get {
                return ResourceManager.GetString("TaxId", resourceCulture);
            }
        }
    }
}
