//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility.ErrorManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResErrorMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResErrorMsg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utility.ErrorManagement.ResErrorMsg", typeof(ResErrorMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval coditions collapsed!.
        /// </summary>
        public static string ApprovalConditionCollapsed {
            get {
                return ResourceManager.GetString("ApprovalConditionCollapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval name has already existed!.
        /// </summary>
        public static string ApprovalNameExisted {
            get {
                return ResourceManager.GetString("ApprovalNameExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the approval stage!.
        /// </summary>
        public static string ApprovalStageNotFound {
            get {
                return ResourceManager.GetString("ApprovalStageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bank account has already existed!.
        /// </summary>
        public static string BankAccountExisted {
            get {
                return ResourceManager.GetString("BankAccountExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used bank account could be modified!.
        /// </summary>
        public static string BankAccountUsed {
            get {
                return ResourceManager.GetString("BankAccountUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bank name has already existed!.
        /// </summary>
        public static string BankNameExisted {
            get {
                return ResourceManager.GetString("BankNameExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The brand has already existed!.
        /// </summary>
        public static string BrandExisted {
            get {
                return ResourceManager.GetString("BrandExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The commodity type has already existed!.
        /// </summary>
        public static string CommodityTypeExisted {
            get {
                return ResourceManager.GetString("CommodityTypeExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin has existed!.
        /// </summary>
        public static string CountryExisted {
            get {
                return ResourceManager.GetString("CountryExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency name or code has existed!.
        /// </summary>
        public static string CurrencyExisted {
            get {
                return ResourceManager.GetString("CurrencyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currency could not be found!.
        /// </summary>
        public static string CurrencyNotFound {
            get {
                return ResourceManager.GetString("CurrencyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to delete!.
        /// </summary>
        public static string DeleteErr {
            get {
                return ResourceManager.GetString("DeleteErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to delete due to the foreign key limitation!.
        /// </summary>
        public static string DeleteFKErr {
            get {
                return ResourceManager.GetString("DeleteFKErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是自动生成的单据，不能删除!.
        /// </summary>
        public static string DeleteRelQuotaConnected {
            get {
                return ResourceManager.GetString("DeleteRelQuotaConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BL has connected with commercial invoice, so could not be delete!.
        /// </summary>
        public static string DeliveryCommercialInvoiceConnected {
            get {
                return ResourceManager.GetString("DeliveryCommercialInvoiceConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BL has connected with delivery, so could not be deleted!.
        /// </summary>
        public static string DeliveryDeliveryConnected {
            get {
                return ResourceManager.GetString("DeliveryDeliveryConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BL has connected with letter of credit, so could not be delete!.
        /// </summary>
        public static string DeliveryLCConnected {
            get {
                return ResourceManager.GetString("DeliveryLCConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some DeliveryLine doesn&apos;t has TempUnitPrice!.
        /// </summary>
        public static string DeliveryLineNotHasTempUnitPrice {
            get {
                return ResourceManager.GetString("DeliveryLineNotHasTempUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BL has connected with payment request, so could not be deleted!.
        /// </summary>
        public static string DeliveryPaymentRequestConnected {
            get {
                return ResourceManager.GetString("DeliveryPaymentRequestConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BL has connected with warehouse-in, so could not be deleted!.
        /// </summary>
        public static string DeliveryWarehouseInConnected {
            get {
                return ResourceManager.GetString("DeliveryWarehouseInConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document could not be found!.
        /// </summary>
        public static string DocumentNotFound {
            get {
                return ResourceManager.GetString("DocumentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delivery No. has already existed!.
        /// </summary>
        public static string DuplicatedDeliveryNo {
            get {
                return ResourceManager.GetString("DuplicatedDeliveryNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID No. is duplicated!.
        /// </summary>
        public static string DuplicatedDeliveryPersonInfo {
            get {
                return ResourceManager.GetString("DuplicatedDeliveryPersonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是自动生成的单据，不能编辑!.
        /// </summary>
        public static string EditRelQuotaConnected {
            get {
                return ResourceManager.GetString("EditRelQuotaConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect service!.
        /// </summary>
        public static string EndpointNotFound {
            get {
                return ResourceManager.GetString("EndpointNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pricing date is beyond the pricing date range in the quota!.
        /// </summary>
        public static string ExceedPricingDateRange {
            get {
                return ResourceManager.GetString("ExceedPricingDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to fetch unread transactions!.
        /// </summary>
        public static string FetchUnreadTransErr {
            get {
                return ResourceManager.GetString("FetchUnreadTransErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It has been connected with final invoice so could not be deleted!.
        /// </summary>
        public static string FinalInvoiceIdExisted {
            get {
                return ResourceManager.GetString("FinalInvoiceIdExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to create new account because the superior account has already attached to payment usage!.
        /// </summary>
        public static string FinancialAccountAddFKErr {
            get {
                return ResourceManager.GetString("FinancialAccountAddFKErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name has already existed!.
        /// </summary>
        public static string FinancialAccountExisted {
            get {
                return ResourceManager.GetString("FinancialAccountExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial account connected with fund flow, cannot be deleted!.
        /// </summary>
        public static string FinancialAccountFundFlowConnected {
            get {
                return ResourceManager.GetString("FinancialAccountFundFlowConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial account connected with payment usage, cannot be deleted!.
        /// </summary>
        public static string FinancialAccountPaymentUsageConnected {
            get {
                return ResourceManager.GetString("FinancialAccountPaymentUsageConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to update account! It is not allowed to change the superior account for non-end account!.
        /// </summary>
        public static string FinancialAccountUpdate2FKErr {
            get {
                return ResourceManager.GetString("FinancialAccountUpdate2FKErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to update account because the superior account has already attached to payment usage!.
        /// </summary>
        public static string FinancialAccountUpdateFKErr {
            get {
                return ResourceManager.GetString("FinancialAccountUpdateFKErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find Foreign Delivery!.
        /// </summary>
        public static string ForeignDeliveryPoolNotFound {
            get {
                return ResourceManager.GetString("ForeignDeliveryPoolNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LME position in the hedge group could not be found!.
        /// </summary>
        public static string HedgeGroupLineLMEPositionNotFound {
            get {
                return ResourceManager.GetString("HedgeGroupLineLMEPositionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quota in the hedge group could not be found!.
        /// </summary>
        public static string HedgeGroupLineQuotaNotFound {
            get {
                return ResourceManager.GetString("HedgeGroupLineQuotaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SHFE position in the hedge group could not be found!.
        /// </summary>
        public static string HedgeGroupLineSHFEPositionNotFound {
            get {
                return ResourceManager.GetString("HedgeGroupLineSHFEPositionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hedge group could not be found!.
        /// </summary>
        public static string HedgeGroupNotFound {
            get {
                return ResourceManager.GetString("HedgeGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settled hedge group could not be edited!.
        /// </summary>
        public static string HedgeGroupSettledNotForModify {
            get {
                return ResourceManager.GetString("HedgeGroupSettledNotForModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票与付款申请关联，不能删除！.
        /// </summary>
        public static string InvoiceHasPayMentRequest {
            get {
                return ResourceManager.GetString("InvoiceHasPayMentRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LC has connected with commercial invoice, so could not be delete!.
        /// </summary>
        public static string LCCommercialInvoiceConnected {
            get {
                return ResourceManager.GetString("LCCommercialInvoiceConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LME position attached to some hedge group could not be edited or deleted!.
        /// </summary>
        public static string LMEPositionHedged {
            get {
                return ResourceManager.GetString("LMEPositionHedged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LME position could not be found!.
        /// </summary>
        public static string LMEPositionNotFound {
            get {
                return ResourceManager.GetString("LMEPositionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The log action could not be found!.
        /// </summary>
        public static string LogActionNotFound {
            get {
                return ResourceManager.GetString("LogActionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed! Incorrect login name or password!.
        /// </summary>
        public static string LoginFailErr {
            get {
                return ResourceManager.GetString("LoginFailErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login name has existed! .
        /// </summary>
        public static string LoginNameExisted {
            get {
                return ResourceManager.GetString("LoginNameExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not during an approval procedure! .
        /// </summary>
        public static string NotDuringApproval {
            get {
                return ResourceManager.GetString("NotDuringApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the approval or current stage has passed!.
        /// </summary>
        public static string NotInApproval {
            get {
                return ResourceManager.GetString("NotInApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object not found!.
        /// </summary>
        public static string ObjectNotFound {
            get {
                return ResourceManager.GetString("ObjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password input incorrectly!.
        /// </summary>
        public static string OldPasswordErr {
            get {
                return ResourceManager.GetString("OldPasswordErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database changed. Please retry after refresh database!.
        /// </summary>
        public static string OptimisticConcurrencyErr {
            get {
                return ResourceManager.GetString("OptimisticConcurrencyErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment means has already existed!.
        /// </summary>
        public static string PaymentMeanExisted {
            get {
                return ResourceManager.GetString("PaymentMeanExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payment request has connected with fund flow, so could not be deleted!.
        /// </summary>
        public static string PaymentRequestFundFlowConnected {
            get {
                return ResourceManager.GetString("PaymentRequestFundFlowConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payment request has connected with letter of credit, so could not be deleted!.
        /// </summary>
        public static string PaymentRequestLCConnected {
            get {
                return ResourceManager.GetString("PaymentRequestLCConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payment request could not be found!.
        /// </summary>
        public static string PaymentRequestNotFound {
            get {
                return ResourceManager.GetString("PaymentRequestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment usage has already existed!.
        /// </summary>
        public static string PaymentUsageExisted {
            get {
                return ResourceManager.GetString("PaymentUsageExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to save! Default account should be end account! .
        /// </summary>
        public static string PaymentUsagePAExisted {
            get {
                return ResourceManager.GetString("PaymentUsagePAExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port has existed!.
        /// </summary>
        public static string PortExisted {
            get {
                return ResourceManager.GetString("PortExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing currency is not consistent with the one in quota!.
        /// </summary>
        public static string PricingCurrencyNotMatch {
            get {
                return ResourceManager.GetString("PricingCurrencyNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is pricing basing on it so it could not be edited or deleted!.
        /// </summary>
        public static string PricingUnpricingConnected {
            get {
                return ResourceManager.GetString("PricingUnpricingConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quota has been fully priced and opened the VAT invoice, so could not be deleted!.
        /// </summary>
        public static string PricingVATInvoiceConnected {
            get {
                return ResourceManager.GetString("PricingVATInvoiceConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quota connected to commercial invoice could not be deleted!.
        /// </summary>
        public static string QuotaCommercialInvoiceConnected {
            get {
                return ResourceManager.GetString("QuotaCommercialInvoiceConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quota has connected with BL/WR, so could not be deleted!.
        /// </summary>
        public static string QuotaDeliveryConnected {
            get {
                return ResourceManager.GetString("QuotaDeliveryConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quota has connected with fund flow, so could not be deleted!.
        /// </summary>
        public static string QuotaFundFlowConnected {
            get {
                return ResourceManager.GetString("QuotaFundFlowConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quota attached to some hedge group could not be edited or deleted!.
        /// </summary>
        public static string QuotaHedgedNotAbleToDeleteModify {
            get {
                return ResourceManager.GetString("QuotaHedgedNotAbleToDeleteModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quota has connected with letter of credit, so could not be deleted!.
        /// </summary>
        public static string QuotaLetterOfCreditConnected {
            get {
                return ResourceManager.GetString("QuotaLetterOfCreditConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quota doesn&apos;t exist!.
        /// </summary>
        public static string QuotaNotExisted {
            get {
                return ResourceManager.GetString("QuotaNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quota has connected with payment request, so could not be deleted!.
        /// </summary>
        public static string QuotaPaymentRequestConnected {
            get {
                return ResourceManager.GetString("QuotaPaymentRequestConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quota has connected with pricing, so could not be deleted!.
        /// </summary>
        public static string QuotaPricingConnected {
            get {
                return ResourceManager.GetString("QuotaPricingConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quota has connected with VAT invoice, so could not be deleted!.
        /// </summary>
        public static string QuotaVATInvoiceConnected {
            get {
                return ResourceManager.GetString("QuotaVATInvoiceConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quota has connected with VAT invoice request, so could not be deleted!.
        /// </summary>
        public static string QuotaVATInvoiceRequestConnected {
            get {
                return ResourceManager.GetString("QuotaVATInvoiceRequestConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quota has connected with warehouse-out, so could not be deleted!.
        /// </summary>
        public static string QuotaWarehouseOutConnected {
            get {
                return ResourceManager.GetString("QuotaWarehouseOutConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange rate of the currency has existed!.
        /// </summary>
        public static string RateExisted {
            get {
                return ResourceManager.GetString("RateExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role name has already existed!.
        /// </summary>
        public static string RoleNameExisted {
            get {
                return ResourceManager.GetString("RoleNameExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document has been connected with delivery so could not be deleted!.
        /// </summary>
        public static string SaleDeliveryConnected {
            get {
                return ResourceManager.GetString("SaleDeliveryConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SHFE position could not be found!.
        /// </summary>
        public static string SHFEPositionNotFound {
            get {
                return ResourceManager.GetString("SHFEPositionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specification has already existed!.
        /// </summary>
        public static string SpecificationExisted {
            get {
                return ResourceManager.GetString("SpecificationExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String length is beyond the limitation!.
        /// </summary>
        public static string StringOverflow {
            get {
                return ResourceManager.GetString("StringOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Out!.
        /// </summary>
        public static string TimeoutErr {
            get {
                return ResourceManager.GetString("TimeoutErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User define type has existed!.
        /// </summary>
        public static string UdfExisted {
            get {
                return ResourceManager.GetString("UdfExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error!.
        /// </summary>
        public static string UnkownErr {
            get {
                return ResourceManager.GetString("UnkownErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pricing could not be found!.
        /// </summary>
        public static string UnpricingNotFound {
            get {
                return ResourceManager.GetString("UnpricingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pricing quantity exceed the unpriced quantity!.
        /// </summary>
        public static string UnpricingQuantityNotEnough {
            get {
                return ResourceManager.GetString("UnpricingQuantityNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It has been deferred so could not be edited or deleted!.
        /// </summary>
        public static string UnpricingUnpricingConnected {
            get {
                return ResourceManager.GetString("UnpricingUnpricingConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VAT invoice request has been connected with VAT invoice, so could not be deleted!.
        /// </summary>
        public static string VATInvoiceRequestLineConnected {
            get {
                return ResourceManager.GetString("VATInvoiceRequestLineConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT rate has already existed!.
        /// </summary>
        public static string VATRateExisted {
            get {
                return ResourceManager.GetString("VATRateExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse name is already existed!.
        /// </summary>
        public static string WarehouseExisted {
            get {
                return ResourceManager.GetString("WarehouseExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The warehouse-in has connected with warehouse-out, so could not be delete!.
        /// </summary>
        public static string WarehouseInWarehouseOutConnected {
            get {
                return ResourceManager.GetString("WarehouseInWarehouseOutConnected", resourceCulture);
            }
        }
    }
}
