//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.View.Physical.CommercialInvoices {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResCommercialInvoice {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResCommercialInvoice() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.View.Physical.CommercialInvoices.ResCommercialInvoice", typeof(ResCommercialInvoice).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Final Invoice.
        /// </summary>
        public static string AddFinalInvoice {
            get {
                return ResourceManager.GetString("AddFinalInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Provisional Invoice.
        /// </summary>
        public static string AddProvisionalInvoice {
            get {
                return ResourceManager.GetString("AddProvisionalInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount(Interest Included).
        /// </summary>
        public static string AmountIncludingInterest {
            get {
                return ResourceManager.GetString("AmountIncludingInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select BL!.
        /// </summary>
        public static string BLNotNull {
            get {
                return ResourceManager.GetString("BLNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Home.
        /// </summary>
        public static string CommercialInvoiceHome {
            get {
                return ResourceManager.GetString("CommercialInvoiceHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice List.
        /// </summary>
        public static string CommercialInvoiceList {
            get {
                return ResourceManager.GetString("CommercialInvoiceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency is not identical among the related invoices! Not able to be saved!.
        /// </summary>
        public static string CurrencyInconsistentError {
            get {
                return ResourceManager.GetString("CurrencyInconsistentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency is not consistent between provisional invoice and final invoice! Not able to be saved!.
        /// </summary>
        public static string CurrencyInconsistentError2 {
            get {
                return ResourceManager.GetString("CurrencyInconsistentError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency is not consistent between provisional invoice and related LoC. Not able to be saved!.
        /// </summary>
        public static string CurrencyInconsistentError3 {
            get {
                return ResourceManager.GetString("CurrencyInconsistentError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Invoice of the Month.
        /// </summary>
        public static string CurrentMonthFinalInvoice {
            get {
                return ResourceManager.GetString("CurrentMonthFinalInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provisional Invoice of the Month.
        /// </summary>
        public static string CurrentMonthProvisionalInvoice {
            get {
                return ResourceManager.GetString("CurrentMonthProvisionalInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select delivery form!.
        /// </summary>
        public static string DeliveryFormNotNull {
            get {
                return ResourceManager.GetString("DeliveryFormNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The invoice no is already existed!.
        /// </summary>
        public static string InvoiceNoExisted {
            get {
                return ResourceManager.GetString("InvoiceNoExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input invoice No.!.
        /// </summary>
        public static string InvoiceNoNotNull {
            get {
                return ResourceManager.GetString("InvoiceNoNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Type.
        /// </summary>
        public static string InvoiceType {
            get {
                return ResourceManager.GetString("InvoiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select provisional invoice!.
        /// </summary>
        public static string ProvisionalInvoiceNotNull {
            get {
                return ResourceManager.GetString("ProvisionalInvoiceNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Invoice - Final.
        /// </summary>
        public static string PurchaseCommercialInvoiceFinal {
            get {
                return ResourceManager.GetString("PurchaseCommercialInvoiceFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Invoice Home.
        /// </summary>
        public static string PurchaseCommercialInvoiceHome {
            get {
                return ResourceManager.GetString("PurchaseCommercialInvoiceHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase CommercialInvoice List.
        /// </summary>
        public static string PurchaseCommercialInvoiceList {
            get {
                return ResourceManager.GetString("PurchaseCommercialInvoiceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Invoice - Provisional.
        /// </summary>
        public static string PurchaseCommercialInvoiceProvisional {
            get {
                return ResourceManager.GetString("PurchaseCommercialInvoiceProvisional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Invoice No.
        /// </summary>
        public static string RelatedInvoiceNo {
            get {
                return ResourceManager.GetString("RelatedInvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Invoice - Final.
        /// </summary>
        public static string SalesCommercialInvoiceFinal {
            get {
                return ResourceManager.GetString("SalesCommercialInvoiceFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Invoice Home.
        /// </summary>
        public static string SalesCommercialInvoiceHome {
            get {
                return ResourceManager.GetString("SalesCommercialInvoiceHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales CommercialInvoice List.
        /// </summary>
        public static string SalesCommercialInvoiceList {
            get {
                return ResourceManager.GetString("SalesCommercialInvoiceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Invoice - Provisional.
        /// </summary>
        public static string SalesCommercialInvoiceProvisional {
            get {
                return ResourceManager.GetString("SalesCommercialInvoiceProvisional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of shipment is beyond the 50 letters limitation!.
        /// </summary>
        public static string ShipTermError {
            get {
                return ResourceManager.GetString("ShipTermError", resourceCulture);
            }
        }
    }
}
