//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;


namespace DBEntity
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(ForeignDeliveryPool))]
    public partial class FDPStorageFeeSEDate: IObjectWithChangeTracker, INotifyPropertyChanged, IEntity
    {
        #region Primitive Properties
    
        [DataMember]
        public int Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'Id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        private int _id;
    
        [DataMember]
        public bool IsDeleted
        {
            get { return _isDeleted; }
            set
            {
                if (_isDeleted != value)
                {
                    _isDeleted = value;
                    OnPropertyChanged("IsDeleted");
                }
            }
        }
        private bool _isDeleted;
    
        [DataMember]
        public byte[] Ver
        {
            get { return _ver; }
            set
            {
                if (_ver != value)
                {
                    _ver = value;
                    OnPropertyChanged("Ver");
                }
            }
        }
        private byte[] _ver;
    
        [DataMember]
        public Nullable<System.DateTime> Updated
        {
            get { return _updated; }
            set
            {
                if (_updated != value)
                {
                    _updated = value;
                    OnPropertyChanged("Updated");
                }
            }
        }
        private Nullable<System.DateTime> _updated;
    
        [DataMember]
        public Nullable<int> UpdatedBy
        {
            get { return _updatedBy; }
            set
            {
                if (_updatedBy != value)
                {
                    _updatedBy = value;
                    OnPropertyChanged("UpdatedBy");
                }
            }
        }
        private Nullable<int> _updatedBy;
    
        [DataMember]
        public Nullable<System.DateTime> Created
        {
            get { return _created; }
            set
            {
                if (_created != value)
                {
                    _created = value;
                    OnPropertyChanged("Created");
                }
            }
        }
        private Nullable<System.DateTime> _created;
    
        [DataMember]
        public Nullable<int> CreatedBy
        {
            get { return _createdBy; }
            set
            {
                if (_createdBy != value)
                {
                    _createdBy = value;
                    OnPropertyChanged("CreatedBy");
                }
            }
        }
        private Nullable<int> _createdBy;
    
        [DataMember]
        public string Comment
        {
            get { return _comment; }
            set
            {
                if (_comment != value)
                {
                    _comment = value;
                    OnPropertyChanged("Comment");
                }
            }
        }
        private string _comment;
    
        [DataMember]
        public int DeliveryPoolId
        {
            get { return _deliveryPoolId; }
            set
            {
                if (_deliveryPoolId != value)
                {
                    ChangeTracker.RecordOriginalValue("DeliveryPoolId", _deliveryPoolId);
                    if (!IsDeserializing)
                    {
                        if (ForeignDeliveryPool != null && ForeignDeliveryPool.Id != value)
                        {
                            ForeignDeliveryPool = null;
                        }
                    }
                    _deliveryPoolId = value;
                    OnPropertyChanged("DeliveryPoolId");
                }
            }
        }
        private int _deliveryPoolId;
    
        [DataMember]
        public Nullable<decimal> StorageFee
        {
            get { return _storageFee; }
            set
            {
                if (_storageFee != value)
                {
                    _storageFee = value;
                    OnPropertyChanged("StorageFee");
                }
            }
        }
        private Nullable<decimal> _storageFee;
    
        [DataMember]
        public Nullable<decimal> TransferFee
        {
            get { return _transferFee; }
            set
            {
                if (_transferFee != value)
                {
                    _transferFee = value;
                    OnPropertyChanged("TransferFee");
                }
            }
        }
        private Nullable<decimal> _transferFee;
    
        [DataMember]
        public Nullable<decimal> WarrantFee
        {
            get { return _warrantFee; }
            set
            {
                if (_warrantFee != value)
                {
                    _warrantFee = value;
                    OnPropertyChanged("WarrantFee");
                }
            }
        }
        private Nullable<decimal> _warrantFee;
    
        [DataMember]
        public Nullable<System.DateTime> StartDate
        {
            get { return _startDate; }
            set
            {
                if (_startDate != value)
                {
                    _startDate = value;
                    OnPropertyChanged("StartDate");
                }
            }
        }
        private Nullable<System.DateTime> _startDate;
    
        [DataMember]
        public Nullable<System.DateTime> EndDate
        {
            get { return _endDate; }
            set
            {
                if (_endDate != value)
                {
                    _endDate = value;
                    OnPropertyChanged("EndDate");
                }
            }
        }
        private Nullable<System.DateTime> _endDate;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public ForeignDeliveryPool ForeignDeliveryPool
        {
            get { return _foreignDeliveryPool; }
            set
            {
                if (!ReferenceEquals(_foreignDeliveryPool, value))
                {
                    var previousValue = _foreignDeliveryPool;
                    _foreignDeliveryPool = value;
                    FixupForeignDeliveryPool(previousValue);
                    OnNavigationPropertyChanged("ForeignDeliveryPool");
                }
            }
        }
        private ForeignDeliveryPool _foreignDeliveryPool;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
    	static ICollection<string> eagerLoadProperties = new List<string>() { };
    	public ICollection<string> EagerLoadProperties
    	{
    		get { return eagerLoadProperties; }
    	}
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            ForeignDeliveryPool = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupForeignDeliveryPool(ForeignDeliveryPool previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.FDPStorageFeeSEDates.Contains(this))
            {
                previousValue.FDPStorageFeeSEDates.Remove(this);
            }
    
            if (ForeignDeliveryPool != null)
            {
                if (!ForeignDeliveryPool.FDPStorageFeeSEDates.Contains(this))
                {
                    ForeignDeliveryPool.FDPStorageFeeSEDates.Add(this);
                }
    
                DeliveryPoolId = ForeignDeliveryPool.Id;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("ForeignDeliveryPool")
                    && (ChangeTracker.OriginalValues["ForeignDeliveryPool"] == ForeignDeliveryPool))
                {
                    ChangeTracker.OriginalValues.Remove("ForeignDeliveryPool");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("ForeignDeliveryPool", previousValue);
                }
                if (ForeignDeliveryPool != null && !ForeignDeliveryPool.ChangeTracker.ChangeTrackingEnabled)
                {
                    ForeignDeliveryPool.StartTracking();
                }
            }
        }

        #endregion

    }
}
