namespace Utility.ServiceManagement
{
    public enum SvcType
    {
        UserSvc = 0,
        CategorySvc = 1,
        ModuleSvc = 2,
        RoleSvc = 3,
        BankSvc = 4,
        BankAccountSvc = 5,
        CurrencySvc = 6,
        RateSvc = 7,
        WarehouseSvc = 8,
        CommoditySvc = 9,
        CommodityTypeSvc = 10,
        BrandSvc = 11,
        SpecificationSvc = 12,
        CountrySvc = 13,
        BusinessPartnerSvc = 14,
        MarketPriceSvc = 15,
        PortSvc = 16,
        PaymentMeanSvc = 17,
        VATRateSvc = 18,
        ContractSvc = 19,
        SystemParameterSvc = 20,
        PaymentUsageSvc = 21,
        DeliverySvc = 22,
        WarehouseInSvc = 23,
        ApprovalSvc = 25,
        FinancialAccountSvc = 26,
        FundFlowSvc = 27,
        QuotaSvc = 28,
        DeliveryLineSvc = 29,
        WarehouseInLineSvc = 30,
        AttachmentSvc = 31,
        UploadSvc = 32,
        PaymentRequestSvc = 33,
        WarehouseOutSvc = 34,
        LetterOfCreditSvc = 35,
        PricingSvc = 36,
        VATInvoiceRequestSvc=37,
        VATInvoiceRequestLineSvc=38,
        InventorySvc = 39,
        WarehouseOutLineSvc = 40,
        UnpricingSvc = 41,
        CommercialInvoiceSvc=42,
        VATInvoiceSvc = 43,
        VATInvoiceLineSvc = 44,
        DocumentSvc = 45,
        CommissionSvc = 46,
        CommissionLineSvc = 47,
        LMEPositionSvc=48,
        LogRegistrationSvc = 49,
        LogMessageSvc = 50,
        SHFEPositionSvc=51,
        SHFESvc=52,
        HedgeGroupSvc = 53,
        ContractUDFSvc = 54,
        SHFEFundFlowSvc = 55,
        PSQuotaRelSvc=56,
        DeliveryPersonSvc = 57,
        ForeignDeliveryPoolSvc = 58,
        ForeignDeliveryPoolLineSvc = 59,
        LCAllocationSvc = 60
    }
}